### ISSUE TITLE
Add-in won't run due to certificate error

### ISSUE THREAD

**Issue by kew-dev** [OfficeDev/Word-Add-in-Angular2-StyleChecker#10]
Unable to launch Style Checker demo add-in in Word 2016, Windows 10.  Other sample add-ins work, but something is not right w/this particular add-in's certificate on my machine. Error appears at top of task pane: The content is blocked because it isn't signed by a valid security certificate.  Have done the necessary steps to configure project, and tried the suggestions mentioned in 
https://github.com/OfficeDev/generator-office/issues/486 (although changing the bconfig.json file did not work for me, so I reverted to the original). Any tips beyond what has been suggested in #486 would be appreciated.

**Comment by Rick-Kirkham** [comment]
Have  you followed the steps in the [Run the project](https://github.com/OfficeDev/Word-Add-in-Angular2-StyleChecker#run-the-project) section of the Readme? On step 2 of that procedure, do you get a warning? What happens?

**Comment by kew-dev** [comment]
For step 2 of 'Run the project' I have tried this in several different browsers, including IE, Edge and Chrome.  The red 'Not secure' error appears in all the browsers. (Note: The instructions state the I should double-click the error, but that doesn't seem to do anything.) When I click once on the 'Not secure' error, I am prompted with a choice to view the certificate. Attaching screenshot of the browser and dialog that appears when I view the certificate. On the Certification Path tab of the dialog, certificate status shows "This CA Root certificate is not trusted because it is not in the Trusted Root Certification Authorities store."  I've tried removing all listed localhost entries from my certificate store and re-installing the certificate based on the steps in 'Configure the project'.  When I perform the installation steps, the certificate does appear to be installing successfully and I can see the localhost and localhost-ca entries have been added to the certificate store. But the expiration date shown in the local host entries of the Trusted Root Certification Authorities does not match the expiration date of the certificate that appears when I click on the 'Not secure' error.  

![image](https://user-images.githubusercontent.com/73360594/99463122-eb978980-28e9-11eb-8247-b4a916661321.png)

**Comment by Rick-Kirkham** [comment]
I can reproduce this. Those steps for trusting the cert no longer work with contemporary browsers. I will see if I can find some help internally for redoing the certificate parts of this sample.

**Comment by Rick-Kirkham** [comment]
While we're waiting. Try this PowerShell command (opened as administrator). Replace the "C:\Users\Xyz\Desktop\BackupCert.Cer" with the full path to the ca.crt file in the root of the project (in quotation marks).

`Import-Certificate -FilePath "C:\Users\Xyz\Desktop\BackupCert.Cer" -CertStoreLocation cert:\LocalMachine\Root`

See if this fixes it.

**Comment by kew-dev** [comment]
Thank you for your assistance, Rick!   I removed the local certificate from the store and tried your suggestion from PowerShell.  After running the command, the following response appears in PowerShell:

   PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\Root

Thumbprint                                Subject
----------                                -------
5B668AE190F9519A97F7DF86A2ADF7347FF915B1  CN=localhost-ca, OU=word-add-in-angular2-stylechecker, O=MaxDevAddins, L=Redmond, S=WA, C=US

But the outcome, when I proceed through the steps to run the add-in, is the same as what I originally reported.

It should not be necessary to remove and re-add the Add-in manifest from the Word UI, correct?

**Comment by Rick-Kirkham** [comment]
I don't think re-adding the add-in will help, but it can't hurt to try.

**Comment by Rick-Kirkham** [comment]
@kew-dev Are you interested in the sample simply because you want to see an add-in that uses Angular? Or are you interested in what the add-in does with the Word doc? I'm asking because the Yo Office tool has an option to create an Angular add-in. Go through this [Word QuickStart](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator), but when the Yo Office tool prompts you to choose a project type, choose the Angular option. 

![image](https://user-images.githubusercontent.com/9088056/99582543-1be93180-2997-11eb-80fa-03a01981ff86.png)

**Comment by kew-dev** [comment]
@Rick-Kirkham It's a pretty awesome sample, and I'm using it to understand the concepts presented.  While running it isn't critical, it would be nice to be able to at some point.

**Comment by Rick-Kirkham** [comment]
I've found a workaround that works for me. See if it works and I'll update the readme.

1. Carry out the steps of the [Word Quickstart](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator). (It doesn't matter what project type you choose. The only reason you are doing this is because the process will cause certs to be created at **c:\users\YOUR-USER-NAME\.office-addin-dev-certs**. )

2. When you first start the project, you will be prompted to accept a certificate. Follow the instructions to accept it.

3. Once you've verified that the quickstart project opens and works, close Word. 

4. Optional: Verify that the **c:\users\YOUR-USER-NAME\.office-addin-dev-certs** folder was created and that there are 3 cert files in it.

5. Go back to your clone of this repo. 

6. Open the bs-config.json file in the root of the project. Replace it's contents with the following. (Replace YOUR-USER-NAME with your user name.) (Note that the slashes are forward, even though this is a Windows path.)

```
{
    "https": {
        "key": "c:/users/YOUR-USER-NAME/.office-addin-dev-certs/localhost.key",
        "cert": "c:/users/YOUR-USER-NAME/.office-addin-dev-certs/localhost.crt"
    }
}
```

7. Resume the Readme of this project with the **Run the sample** section. (In my case, the Edge window opened automatically and the certificate error had gone away, so I was able to skip down to the **Start the add-in** section.)

**Comment by kew-dev** [comment]
After doing the above steps, the following error occurs after typing 'npm start' in the command window. 

![image](https://user-images.githubusercontent.com/73360594/99610489-c9c00480-29c6-11eb-98a3-5862b8131bdb.png)

(Note: I received a similar error when attempted the workaround from https://github.com/OfficeDev/generator-office/issues/486 before submitting this issue.)

If there's no 'easy' way to get the certificate working with this code sample, maybe we should close the issue and I'll move on to some others.

**Comment by Rick-Kirkham** [comment]
I get that same error, but it doesn't prevent the server from running or the add-in from working. You can see by the last line in your screenshot that the server is up and running and waiting for changes. Please continue with the **Start the add-in** section and see if the add-in runs.

**Comment by kew-dev** [comment]
With the latest attempt, the "Style Checker" task pane does display in Word, but something is off -- instead of seeing the expected UI, I see the contents of a directory. The manifest.xml and README.md included in this listing appear to be from the Word Quickstart, rather than the Style Checker.  

Attaching screenshot of what appears both in Edge and in the Style Checker TaskPane.  FYI, my background is Word add-in developer (COM), not web developer. I am trying to understand all these concepts and may be missing something obvious here. But I would expect to see what is defined by the manifest "Word-Add-in-Angular2-StyleChecker.xml", and that is what I was seeing originally in Edge after running npm start (as shown in original screenshot).  I have verified I am in the correct folder for the Style Checker add-in when I issue the npm start command at the command prompt. 

![image](https://user-images.githubusercontent.com/73360594/99742682-e3c21b80-2a88-11eb-9c5a-cf5b3e57a0e5.png)

Thanks again for your help.

**Comment by Rick-Kirkham** [comment]
I think that what is happening is that the server for the quickstart project is still running and processing requests to localhost:3000.  But when the project from _this sample_ asks for instruction-steps, there is no route/file with that name in the quickstart project so the server is defaulting to a directory view. 

Since you now have the certs in your user folder, you don't need the quickstart project anymore. Please just delete it and reboot the machine to ensure that the server from that project is not running. Then go back to this sample and start again with the **Run the add-in** section. That will start the server from _this_ project at localhost:3000.

**Comment by kew-dev** [comment]
I rebooted and have run through all the steps... this time, LocalHost is no longer working at all.  After npm start, I open Edge and an error appears: localhost refused to connect (ERR_CONNECTION_REFUSED).  I'm not one to give up, but I think I may need to move on unless you know of anything else I can do to make this particular sample run.

**Comment by Rick-Kirkham** [comment]
Sorry the workaround doesn't work for you. It works for me. I don't know why you are getting such an odd result.

**Comment by Rick-Kirkham** [comment]
I've update the sample to use the new certs system. I've validated that it works on a clean machine. Updated the readme too.

**Comment by kew-dev** [comment]
@Rick-Kirkham Thank you, I just went through the steps and the sample add-in is now working as expected.
